# Календарные гипотезы о спросе на билеты

Проверяем нелинейные сочетания, явное линейное взаимодействие и относительные
календарные поправки с внутренним подбором штрафа, а также общий спрос
с распределением по сезонным долям зон. Отклонение — это разница итогового спроса и среднего своей зоны
и сезона в обучающей истории. Все модели учат именно это отклонение.

Общий код берём из выбранного ноутбука, сохраняя подготовку данных, сезонный
уровень, поправку продаж и ограничения. Финальный расчёт test не запускаем;
этот эксперимент не записывает прогнозы для сдачи.

Используем согласованный для этой серии сценарный протокол: три окна,
утро открытия и утро O+27/O+7, единая выборка L≥28. Поздний раздел
«Режим финального дня» в PROTOCOL задаёт другой режим; в этой серии по прямому
поручению применяем сценарный режим исходного решения, чтобы сравнение было
сопоставимым. PROTOCOL остаётся без изменений.

Все три окна уже участвовали в выборе текущей модели. Независимой итоговой
оценки нет; заранее ограниченная серия не устраняет это ограничение.

In [1]:
from pathlib import Path
import nbformat
from catboost import CatBoostRegressor

root = Path.cwd()
if root.name == "notebooks":
    root = root.parent

source = nbformat.read(root / "notebooks/Avangard_ticket_demand.ipynb", as_version=4)
# Только подготовка и общие функции; нет ячейки сохранения итогового CSV.
common_cells = [1, 3, 5, 7, 9, 11, 13, 15, 17]
for number in common_cells:
    exec(compile(source.cells[number].source, f"Avangard_cell_{number}", "exec"))

Обучение: 85 матчей, 680 пар матч–зона.

scenario   Без продаж  С продажами  С продажами, L 28–42
window
M035–M051          17           10                    10
M052–M068          17           17                    12
M069–M085          17            9                     9

## 1. Заранее фиксируем варианты

А: сезонный уровень + 80% отклонения Ridge(alpha=10) + 20% отклонения CatBoost.
Б: сезонный уровень + Ridge(alpha=30), исходные признаки и категория zone×weekday.
Это одновременно взаимодействие и более сильный штраф; результат нельзя
приписать только взаимодействию.
В: 80% среднего зоны + 20% полного календарного прогноза CatBoost.

В А и В используется один и тот же CatBoost. Во всех трёх кандидатах после
смешивания календарных прогнозов применяется прежняя поправка ранних продаж.
В — смесь календарных прогнозов с общей поправкой, а не смесь полных итогов.
Baseline остаётся обычным средним зоны с общими границами, без модельной поправки.

CatBoost строит небольшие деревья: несколько последовательных вопросов о
признаках позволяют учитывать их сочетания. Глубина 3 ограничивает число
таких вопросов. Штраф 10 сдерживает случайные эффекты малой истории.
Число деревьев и веса не выбираются по проверочным ответам.

Для воспроизведения установите `catboost==1.2.8` дополнительно к
`requirements.txt` и выполните этот ноутбук сверху вниз. Версии запуска: Python 3.12.14; CatBoost 1.2.8; numpy 2.3.5; pandas 3.0.1; scikit-learn 1.7.2.

In [2]:
catboost_params = dict(
    iterations=300, depth=3, learning_rate=0.03, l2_leaf_reg=10,
    loss_function="RMSE", random_seed=42, use_best_model=False,
    thread_count=2, allow_writing_files=False, verbose=False,
)
interaction_alpha = 30
catboost_weight = 0.2
method_names = ["Baseline", "Текущая Ridge", "А: Ridge 80% + CB 20%",
                "Б: Ridge zone×weekday", "В: baseline 80% + CB 20%"]
print("CatBoost:", catboost_params)
print("Ridge взаимодействия: alpha=", interaction_alpha)

CatBoost: {'iterations': 300, 'depth': 3, 'learning_rate': 0.03, 'l2_leaf_reg': 10, 'loss_function': 'RMSE', 'random_seed': 42, 'use_best_model': False, 'thread_count': 2, 'allow_writing_files': False, 'verbose': False}
Ridge взаимодействия: alpha= 30

## 2. Учим календарные отклонения на доступной истории

Категорию zone×weekday можно представить как отдельную метку «зона 6,
суббота»: она позволяет линейной модели учитывать особую связь дня недели
с конкретной зоной. CatBoost получает исходные категории непосредственно.

Средние обучающих ответов, кодирование, масштабирование и обе модели
обучаются только на history. Истинные итоги query в функции не передаются.
CatBoost не получает eval_set и не останавливается по проверочному окну.

In [3]:
def interaction_features(frame):
    # Доступен на момент: расписание и зона известны до открытия продаж.
    features = model_features(frame)
    features["zone_weekday"] = features["zone"] + "_" + features["weekday"]
    return features


def alternative_calendars(history, query):
    # Доступен на момент: завершённая история и известное расписание query.
    centers = history.groupby(["zone", "season"])["tickets_total"].transform("mean")
    deviations = history["tickets_total"] - centers
    level = season_level(history, query)
    current = calendar_forecast(history, query)
    baseline = zone_mean(history, query)

    catboost = CatBoostRegressor(**catboost_params)
    catboost.fit(model_features(history), deviations, cat_features=categorical_features)
    catboost_deviation = catboost.predict(model_features(query))
    catboost_calendar = level + catboost_deviation

    categories = categorical_features + ["zone_weekday"]
    preprocessing = ColumnTransformer([
        ("categories", OneHotEncoder(handle_unknown="ignore", sparse_output=False), categories),
        ("number", StandardScaler(), numeric_features),
    ])
    ridge = make_pipeline(preprocessing, Ridge(alpha=interaction_alpha, random_state=42))
    ridge.fit(interaction_features(history), deviations)
    interaction = level + ridge.predict(interaction_features(query))

    return {
        method_names[0]: baseline,
        method_names[1]: current,
        method_names[2]: (1 - catboost_weight) * current + catboost_weight * catboost_calendar,
        method_names[3]: interaction,
        method_names[4]: (1 - catboost_weight) * baseline + catboost_weight * catboost_calendar,
    }

## 3. Сохраняем общую поправку собственных продаж

Каждый кандидат получает одну и ту же поправку, рассчитанную на завершённых
аналогах при одинаковом числе дней до игры. Меняется только ожидаемый полный
итог до поправки: поэтому ожидаемые ранние продажи тоже соответствуют
новому календарному прогнозу. Baseline остаётся исходным ориентиром.

In [4]:
def add_sales_correction(history, query, initial):
    prediction = pd.Series(initial, index=query.index)
    for match_id, match_query in query.loc[query["has_sales"]].groupby("match_id"):
        cutoff = match_query["cutoff"].iloc[0]
        analogs = matched_history(history, match_id, cutoff)
        base = prediction.loc[match_query.index].to_numpy()
        prediction.loc[match_query.index] += sales_correction(analogs, match_query, base)
    return prediction.to_numpy()

## 4. Проверяем все методы на одинаковых примерах

Для каждого утра history содержит только матчи до начала окна и с датой
строго раньше cutoff. Все восемь зон сохраняются вместе. Проверочные матчи
не добавляются в историю даже после завершения внутри окна.

Продажи query берутся строго до cutoff; ответы присоединяются только после
получения прогноза. Для всех методов одинаковы округление floor(p+0.5),
минимум sold и максимум seats. Исторические итоговые абонементы исключены.
Фиксированная выборка содержит 984 прогноза на метод.

In [5]:
import time

started = time.perf_counter()
actual_totals = train.set_index(keys)["tickets_total"]
result_parts = []
group_count = examples.groupby(["window", "cutoff"]).ngroups
for step, ((window, cutoff), query) in enumerate(
    examples.groupby(["window", "cutoff"]), start=1
):
    first_id = query["window_start"].iloc[0]
    history = train.loc[(train["match_id"] < first_id) & (train["date"] < cutoff)]
    calendars = alternative_calendars(history, query)
    for name, initial in calendars.items():
        raw = initial if name == "Baseline" else add_sales_correction(history, query, initial)
        prediction = apply_bounds(raw, query["sold"], query["seats"])
        detail = query[
            keys + ["window", "scenario", "days_observed", "weight", "sales_length"]
        ].copy()
        detail["prediction"] = prediction
        # Ответ присоединяем только после обучения и прогноза.
        pairs = pd.MultiIndex.from_frame(query[keys])
        detail["tickets_total"] = actual_totals.reindex(pairs).to_numpy()
        detail["method"] = name
        detail["squared_error"] = (detail["prediction"] - detail["tickets_total"]) ** 2
        result_parts.append(detail)
    if step % 20 == 0 or step == group_count:
        print(f"Проверено отсечек: {step}/{group_count}")

validation = pd.concat(result_parts, ignore_index=True)
print(f"Время сравнения пяти методов: {time.perf_counter() - started:.1f} с")

Проверено отсечек: 20/47

Проверено отсечек: 40/47

Проверено отсечек: 47/47
Время сравнения пяти методов: 304.1 с

## 5. Считаем ошибки по сценарию и окну

Сначала смешиваем квадраты ошибок 27/7 с весами 2/3 и 1/3 внутри пары
матч–зона. Затем усредняем пары. Ошибка окна R смешивает квадраты сценарных
ошибок с весами 11/17 и 6/17. S — среднее R с весами 0.25/0.25/0.5.
Показываем также диагностику похожих сроков продаж L=28–42.

In [6]:
validation["weighted_error"] = validation["weight"] * validation["squared_error"]
pair_errors = validation.groupby(
    ["method", "window", "scenario"] + keys
)["weighted_error"].sum().reset_index()
scenario_mse = pair_errors.groupby(
    ["method", "window", "scenario"]
)["weighted_error"].mean().unstack("scenario")
window_results = np.sqrt(scenario_mse)
window_results["R"] = np.sqrt(
    (11 / 17) * scenario_mse["Без продаж"] + (6 / 17) * scenario_mse["С продажами"]
)
similar = validation.loc[
    (validation["scenario"] == "С продажами") & validation["sales_length"].between(28, 42)
]
similar_pairs = similar.groupby(["method", "window"] + keys)["weighted_error"].sum()
window_results["С продажами, L 28–42"] = np.sqrt(
    similar_pairs.groupby(["method", "window"]).mean()
)
display(window_results.reindex(method_names, level="method").round(3))

window_weights = np.array([0.25, 0.25, 0.50])
score_rows = []
for name in method_names:
    group = window_results.loc[name].sort_index()
    score_rows.append({
        "Метод": name,
        "R1": group["R"].iloc[0], "R2": group["R"].iloc[1], "R3": group["R"].iloc[2],
        "S без продаж": window_weights @ group["Без продаж"].to_numpy(),
        "S с продажами": window_weights @ group["С продажами"].to_numpy(),
        "S": window_weights @ group["R"].to_numpy(),
    })
scores = pd.DataFrame(score_rows).set_index("Метод")
scores["Изменение S, %"] = 100 * (scores["S"] / scores.loc["Текущая Ridge", "S"] - 1)
display(scores.round(3))

scenario                            Без продаж  С продажами        R  \
method                   window
Baseline                 M035–M051     155.995      151.394  154.386
                         M052–M068     105.410      102.931  104.542
                         M069–M085     157.123      132.333  148.846
Текущая Ridge            M035–M051     156.285      136.536  149.613
                         M052–M068      73.740       66.976   71.426
                         M069–M085     150.871      127.162  142.952
А: Ridge 80% + CB 20%    M035–M051     157.889      138.189  151.229
                         M052–M068      72.308       65.717   70.052
                         M069–M085     151.120      127.515  143.234
Б: Ridge zone×weekday    M035–M051     154.890      136.006  148.499
                         M052–M068      73.359       66.614   71.052
                         M069–M085     151.782      128.164  143.890
В: baseline 80% + CB 20% M035–M051     155.942      133.745  148.487
                         M052–M068      96.051       87.385   93.085
                         M069–M085     155.805      127.763  146.522

scenario                            С продажами, L 28–42
method                   window
Baseline                 M035–M051               151.394
                         M052–M068                99.279
                         M069–M085               132.333
Текущая Ridge            M035–M051               136.536
                         M052–M068                65.291
                         M069–M085               127.162
А: Ridge 80% + CB 20%    M035–M051               138.189
                         M052–M068                64.736
                         M069–M085               127.515
Б: Ridge zone×weekday    M035–M051               136.006
                         M052–M068                64.411
                         M069–M085               128.164
В: baseline 80% + CB 20% M035–M051               133.745
                         M052–M068                84.200
                         M069–M085               127.763

,R1,R2,R3,S без продаж,S с продажами,S,"Изменение S, %"
Метод,,,,,,,
Baseline,154.386,104.542,148.846,143.913,129.748,139.155,9.799
Текущая Ridge,149.613,71.426,142.952,132.941,114.459,126.736,0.000
А: Ridge 80% + CB 20%,151.229,70.052,143.234,133.109,114.734,126.937,0.159
Б: Ridge zone×weekday,148.499,71.052,143.890,132.953,114.737,126.833,0.076
В: baseline 80% + CB 20%,148.487,93.085,146.522,140.901,119.164,133.654,5.459

## 6. Решение по заранее согласованным порогам

Нужны одновременно: снижение S не менее 2%, улучшение хотя бы двух окон,
ухудшение третьего не больше 3% и ухудшение любого сценарного S не больше 3%.
Если критерии не выполнены, сохраняем текущую модель. Отрицательное изменение
S означает улучшение. Порог — практическое правило выбора, а не доказательство
статистической значимости.

In [7]:
current = scores.loc["Текущая Ridge"]
acceptance_rows = []
for name in method_names[2:]:
    row = scores.loc[name]
    improved_windows = sum(row[f"R{i}"] < current[f"R{i}"] for i in (1, 2, 3))
    conditions = [row["S"] <= 0.98 * current["S"], improved_windows >= 2,
                  row["R3"] <= 1.03 * current["R3"],
                  row["S без продаж"] <= 1.03 * current["S без продаж"],
                  row["S с продажами"] <= 1.03 * current["S с продажами"]]
    acceptance_rows.append({
        "Метод": name, "Выигрыш ≥2%": conditions[0], "Окон лучше": improved_windows,
        "Окно 3 допустимо": conditions[2], "Без продаж допустимо": conditions[3],
        "С продажами допустимо": conditions[4], "Принять": all(conditions),
    })
acceptance = pd.DataFrame(acceptance_rows).set_index("Метод")
display(acceptance)

# Контроль воспроизведения исходной оценки, не подбор параметров.
reference = np.array([139.154980934, 126.735841108])
if not np.allclose(scores.loc[method_names[:2], "S"], reference, rtol=0, atol=1e-8):
    raise ValueError("Исходные оценки не воспроизвелись: сравнение нужно проверить.")
print("Baseline и текущая модель воспроизведены.")

,Выигрыш ≥2%,Окон лучше,Окно 3 допустимо,Без продаж допустимо,С продажами допустимо,Принять
Метод,,,,,,
А: Ridge 80% + CB 20%,False,1,True,True,True,False
Б: Ridge zone×weekday,False,2,True,True,True,False
В: baseline 80% + CB 20%,False,1,True,False,False,False

Baseline и текущая модель воспроизведены.

## 7. Диагностика по зонам

Для каждой зоны считаем R с теми же сценарными весами. Таблица содержит
восемь зон; она помогает объяснить результат, но не задаёт новые параметры
для отдельных зон. Параметры серии после просмотра ошибок не меняем.

In [8]:
zone_mse = pair_errors.groupby(
    ["method", "zone", "window", "scenario"]
)["weighted_error"].mean().unstack("scenario")
zone_rmse = np.sqrt(
    (11 / 17) * zone_mse["Без продаж"] + (6 / 17) * zone_mse["С продажами"]
)
for window in window_results.index.get_level_values("window").unique():
    print(window)
    display(zone_rmse.xs(window, level="window").unstack("method")[method_names].round(1))

M035–M051

method,Baseline,Текущая Ridge,А: Ridge 80% + CB 20%,Б: Ridge zone×weekday,В: baseline 80% + CB 20%
zone,,,,,
1,49.5,73.2,70.6,67.3,56.1
2,62.0,63.7,64.9,56.7,57.6
3,70.2,82.7,83.5,76.2,69.5
4,126.0,139.3,148.4,147.1,140.3
5,148.2,141.1,139.7,138.0,136.1
6,336.1,311.5,313.0,309.6,319.4
7,156.2,145.3,146.9,147.4,144.9
8,65.4,73.0,75.8,67.6,61.9

M052–M068

method,Baseline,Текущая Ridge,А: Ridge 80% + CB 20%,Б: Ridge zone×weekday,В: baseline 80% + CB 20%
zone,,,,,
1,45.1,38.2,36.0,33.6,39.7
2,29.6,35.1,31.8,28.7,28.0
3,57.3,68.9,66.8,65.2,58.8
4,117.6,78.5,75.5,83.2,98.5
5,111.4,99.6,96.3,105.0,102.5
6,209.6,75.6,74.5,69.3,181.2
7,85.7,96.2,97.6,93.9,84.3
8,60.9,48.2,49.4,51.1,58.2

M069–M085

method,Baseline,Текущая Ridge,А: Ridge 80% + CB 20%,Б: Ridge zone×weekday,В: baseline 80% + CB 20%
zone,,,,,
1,31.5,44.5,41.4,34.3,30.6
2,55.1,43.3,41.1,39.3,50.4
3,74.4,69.4,69.0,63.2,70.3
4,137.9,148.7,150.5,152.7,139.5
5,118.6,113.2,114.1,112.2,118.4
6,272.9,273.7,273.4,278.1,271.2
7,232.5,206.2,207.4,207.1,225.4
8,77.9,49.0,50.2,52.7,74.2

## 8. Проверка на утечки и границы выводов

1. Расписание и zone×weekday известны до прогноза; комментарии доступности
есть в функциях. КХЛ и исторические итоговые абонементы не входят в признаки.
2. Центры обучающих ответов и сезонный уровень считаются только из history.
Центрирование ответа — преобразование обучающей цели, не признак query.
3. Продажи строго до cutoff; примеры и веса одинаковы у всех пяти методов.
Аналоги завершены к cutoff, собственные их срезы раньше даты игры.
4. Окна идут по времени, все зоны матча вместе; проверочные матчи не пополняют history.
5. Encoder, scaler, Ridge и CatBoost обучаются только на history. CatBoost
не видит проверочных ответов при обучении, eval_set или выборе числа деревьев.
6. Исторические границы sold/seats и округление общие. Test не рассчитываем;
финальный CSV остаётся без изменений. Историческая доступность seats —
согласованное допущение, доступность финальных абонементов не установлена.
7. Контроль исходных двух оценок выполняется программно. Все новые числа
описывают повторно использованные окна выбора; независимой итоговой оценки нет.

## 9. Вывод

Сохраняем текущую Ridge с сезонным уровнем и прежней поправкой продаж.
Ни один кандидат не выполнил заранее заданные условия принятия.

- А: S=126.937 против 126.736, ухудшение 0.159%; лучше только второе окно.
  Малый вклад нелинейной модели не дал общего выигрыша.
- Б: S=126.833, ухудшение 0.076%; первое и второе окна лучше, третье хуже.
  В последнем окне ошибка зоны 6 выросла с 273.7 до 278.1 билета.
  Взаимодействие и более сильный штраф оценивались вместе.
- В: S=133.654, ухудшение 5.459%; сценарные S ухудшились больше 3%.
  Большой вес среднего зоны ослабил полезную календарную часть текущей модели.

Числа округлены для чтения; критерии считались по полной точности.
Вариант А немного улучшил второе окно, а Б — два первых, но локальные
улучшения не превратились в снижение итогового S. Это результаты именно
зафиксированных конфигураций; они не доказывают бесполезность CatBoost вообще.

Сравнение пяти методов заняло 304.1 с в этом окружении. Кандидаты с CatBoost
добавляют ещё одну модель и зависимость без измеренного выигрыша; явное
линейное взаимодействие проще, но тоже не оправдало замену.

Проверка доступности данных пройдена. Ограничение оценки сохраняется:
все три окна уже участвовали в выборе, поэтому истинная ошибка скрытого
test неизвестна и независимой итоговой оценки здесь нет.

## 10. Относительная календарная поправка

Проверяем изменение спроса в долях среднего своей зоны и сезона.
Обучающий ответ r=(y-center)/center. До продаж прогноз P0=season_level*(1+r_hat).
Тот же календарный эффект теперь масштабируется уровнем зоны.

При обучении вес строки равен center² / mean(center²): ошибка в долях
переводится обратно в ошибку в билетах. Нормируем веса до среднего 1,
чтобы штраф оставался управляемым. Это относительная модель с взвешенным
обучением; эффект нельзя приписать одному преобразованию ответа.
Нулевой center заменяем единицей для деления; календарные признаки прежние.

Первая проверка: Ridge(alpha=10), prior=8, поправка продаж 0.5, seed=42.
Далее ограниченный grid search только для этой модели: alpha ∈ {1,10,100}.
Внешние окна, сценарные веса, границы и критерии принятия прежние.
Финальные артефакты не записываем.

In [9]:
from threadpoolctl import threadpool_limits

relative_alpha = 10
alpha_grid = [1, 10, 100]
relative_name = "Относительная Ridge, alpha=10"
grid_name = "Относительная Ridge, внутренний grid"


@threadpool_limits.wrap(limits=1, user_api="blas")
def relative_calendar(history, query, alpha=relative_alpha):
    # Доступен на момент: центры/веса только history, расписание известно заранее.
    centers = history.groupby(["zone", "season"])["tickets_total"].transform("mean")
    scale = centers.clip(lower=1)
    relative_target = (history["tickets_total"] - centers) / scale
    weights = scale ** 2 / np.mean(scale ** 2)
    preprocessing = ColumnTransformer([
        ("categories", OneHotEncoder(handle_unknown="ignore", sparse_output=False),
         categorical_features),
        ("number", StandardScaler(), numeric_features),
    ])
    model = make_pipeline(preprocessing, Ridge(alpha=alpha, random_state=42))
    model.fit(model_features(history), relative_target, ridge__sample_weight=weights)
    relative_change = model.predict(model_features(query))
    return season_level(history, query) * (1 + relative_change)

### Общая проверка календарной функции

Используем выбранные ранее примеры. История заново ограничивается по окну
и утру прогноза. Истинные ответы присоединяются после прогноза и общих границ.
Baseline остаётся средним зоны без модельной поправки; остальные методы
получают прежнюю поправку ранних продаж.

In [10]:
def evaluate_calendar(calendar_function, name):
    parts = []
    for (window, cutoff), query in examples.groupby(["window", "cutoff"]):
        first_id = query["window_start"].iloc[0]
        history = train.loc[(train["match_id"] < first_id) & (train["date"] < cutoff)]
        initial = calendar_function(history, query)
        raw = initial if name == "Baseline" else add_sales_correction(history, query, initial)
        prediction = apply_bounds(raw, query["sold"], query["seats"])
        detail = query[
            keys + ["window", "scenario", "days_observed", "weight", "sales_length"]
        ].copy()
        detail["prediction"] = prediction
        # Доступен только оценке после прогноза: окончательный ответ query.
        pairs = pd.MultiIndex.from_frame(query[keys])
        detail["tickets_total"] = actual_totals.reindex(pairs).to_numpy()
        detail["method"] = name
        detail["squared_error"] = (detail["prediction"] - detail["tickets_total"]) ** 2
        parts.append(detail)
    print("Завершён метод:", name)
    return pd.concat(parts, ignore_index=True)

### Сначала измеряем фиксированный вариант

Baseline и текущую Ridge рассчитываем повторно на тех же примерах.
Проверяем контрольные S. Для сводных таблиц используем уже написанный код
этого ноутбука, без повторения формул в новом разделе.

In [11]:
actual_totals = train.set_index(keys)["tickets_total"]
relative_started = time.perf_counter()
relative_parts = [evaluate_calendar(zone_mean, "Baseline"),
                  evaluate_calendar(calendar_forecast, "Текущая Ridge"),
                  evaluate_calendar(relative_calendar, relative_name)]
method_names = ["Baseline", "Текущая Ridge", relative_name]
validation = pd.concat(relative_parts, ignore_index=True)
series_source = nbformat.read(root / "notebooks/Three_demand_hypotheses.ipynb", as_version=4)
exec(series_source.cells[11].source)
exec(series_source.cells[13].source)

Завершён метод: Baseline
Завершён метод: Текущая Ridge
Завершён метод: Относительная Ridge, alpha=10
Baseline и текущая модель воспроизведены.

scenario                                 Без продаж  ...  С продажами, L 28–42
method                        window                 ...
Baseline                      M035–M051     155.995  ...               151.394
                              M052–M068     105.410  ...                99.279
                              M069–M085     157.123  ...               132.333
Текущая Ridge                 M035–M051     156.285  ...               136.536
                              M052–M068      73.740  ...                65.291
                              M069–M085     150.871  ...               127.162
Относительная Ridge, alpha=10 M035–M051     157.108  ...               137.731
                              M052–M068      74.431  ...                66.052
                              M069–M085     150.199  ...               129.273

[9 rows x 4 columns]

                                    R1       R2  ...        S  Изменение S, %
Метод                                            ...
Baseline                       154.386  104.542  ...  139.155           9.799
Текущая Ridge                  149.613   71.426  ...  126.736           0.000
Относительная Ridge, alpha=10  150.554   71.903  ...  127.196           0.363

[3 rows x 7 columns]

                               Выигрыш ≥2%  ...  Принять
Метод                                       ...
Относительная Ridge, alpha=10        False  ...    False

[1 rows x 6 columns]

## 11. Небольшой grid search внутри истории

Grid search — перебор заранее заданных значений параметра. Здесь три значения
штрафа Ridge: 1,10,100, без поиска весов продаж, новых признаков или параметров CatBoost.
Обычный GridSearchCV со случайными складками для этой задачи не подходит;
используем явный перебор с временными отсечками и нашим сценарным критерием.

Для каждой доступной внешней history берём последние 17 завершённых матчей
как внутреннюю проверку. Перед этим блоком должно оставаться не менее
17 матчей; иначе используем alpha=10 без подбора. Для каждой внутренней
отсечки обучение дополнительно ограничено date<cutoff. Проверочные матчи
внутреннего блока не пополняют его обучение. Внутренние запросы не содержат ответов.

Параметр выбираем по внутреннему R с прежними сценарными весами. Если в блоке
нет матчей L≥28, оставляем alpha=10, поскольку сценарный критерий не определён.
При равенстве ошибок предпочитаем alpha=10, затем больший штраф.
Все ответы внутреннего блока принадлежат завершённой внешней history;
внешние проверочные ответы не участвуют в выборе параметра.
Результат внешних окон по-прежнему не является независимым итоговым тестом.

In [12]:
def internal_examples(history, inner_ids):
    checking = history.loc[history["match_id"].isin(inner_ids)]
    parts = []
    for days, weight in [(0, 1), (27, 2 / 3), (7, 1 / 3)]:
        sample = checking if days == 0 else checking.loc[checking["sales_length"] >= 28]
        sample = sample.drop(columns="tickets_total").copy()
        sample["has_sales"] = days > 0
        sample["scenario"] = "С продажами" if days else "Без продаж"
        sample["weight"] = weight
        sample["cutoff"] = sample["sales_open"] + pd.Timedelta(days=days)
        sample["sold"] = [sales_before(r.match_id, r.zone, r.cutoff)
                          for r in sample.itertuples()]
        parts.append(sample)
    return pd.concat(parts, ignore_index=True)

### Внутренняя ошибка одного значения alpha

Во внутреннем блоке сравниваем все значения на одинаковых примерах.
Считаем также baseline на этом блоке. Поправка продаж и ограничения те же;
полный ответ используется только при расчёте уже полученной ошибки.

In [13]:
def internal_error(history, checking, first_id, alpha):
    parts = []
    answers = history.set_index(keys)["tickets_total"]
    for cutoff, query in checking.groupby("cutoff"):
        fitting = history.loc[(history["match_id"] < first_id) & (history["date"] < cutoff)]
        if alpha is None:
            raw = zone_mean(fitting, query)
        else:
            initial = relative_calendar(fitting, query, alpha)
            raw = add_sales_correction(fitting, query, initial)
        prediction = apply_bounds(raw, query["sold"], query["seats"])
        actual = answers.reindex(pd.MultiIndex.from_frame(query[keys])).to_numpy()
        detail = query[keys + ["scenario", "weight"]].copy()
        detail["error"] = detail["weight"] * (prediction - actual) ** 2
        parts.append(detail)
    detail = pd.concat(parts, ignore_index=True)
    pairs = detail.groupby(["scenario"] + keys)["error"].sum()
    mse = pairs.groupby("scenario").mean()
    return float(np.sqrt((11 / 17) * mse["Без продаж"] + (6 / 17) * mse["С продажами"]))

### Выбор параметра без ответов внешнего окна

Кэш хранит выбор для одной и той же доступной истории. Это сокращает
повторные расчёты; состав истории всегда задаётся внешней отсечкой.
При малой истории не изображаем подбор параметров — явно фиксируем fallback.

In [14]:
grid_cache = {}


def choose_relative_alpha(history):
    # Доступен на момент: только завершённая внешняя history; query сюда не передаётся.
    ids = tuple(sorted(history["match_id"].unique()))
    if ids not in grid_cache:
        record = {"last_history": ids[-1], "history_matches": len(ids), "alpha": 10}
        if len(ids) < 34:
            record["reason"] = "меньше 34 матчей"
        else:
            inner_ids = ids[-17:]
            checking = internal_examples(history, inner_ids)
            record["inner_first"], record["inner_last"] = inner_ids[0], inner_ids[-1]
            if not checking["has_sales"].any():
                record["reason"] = "нет сценария с продажами"
            else:
                errors = {alpha: internal_error(history, checking, inner_ids[0], alpha)
                          for alpha in alpha_grid}
                record["baseline_R"] = internal_error(history, checking, inner_ids[0], None)
                record["errors"] = errors
                record["alpha"] = min(alpha_grid, key=lambda a: (errors[a], a != 10, -a))
                record["reason"] = "внутренняя временная проверка"
        grid_cache[ids] = record
    return grid_cache[ids]["alpha"]


def tuned_relative_calendar(history, query):
    return relative_calendar(history, query, choose_relative_alpha(history))

### Внешнее сравнение фиксированного и подобранного вариантов

Добавляем только одну новую модель с описанным правилом выбора alpha.
Никаких изменений сетки после результатов. Строгие условия принятия
сохраняются для обеих относительных моделей.

In [15]:
relative_parts.append(evaluate_calendar(tuned_relative_calendar, grid_name))
method_names = ["Baseline", "Текущая Ridge", relative_name, grid_name]
validation = pd.concat(relative_parts, ignore_index=True)
exec(series_source.cells[11].source)
exec(series_source.cells[13].source)
exec(series_source.cells[15].source)
choice_counts = pd.Series([r["alpha"] for r in grid_cache.values()]).value_counts().sort_index()
print("Выборы alpha по уникальным историям:", choice_counts.to_dict())
print("С fallback:", sum("errors" not in r for r in grid_cache.values()))
print(f"Относительная модель и grid search: {time.perf_counter() - relative_started:.1f} с")

Завершён метод: Относительная Ridge, внутренний grid
Baseline и текущая модель воспроизведены.
M035–M051
M052–M068
M069–M085
Выборы alpha по уникальным историям: {10: 1, 100: 5}
С fallback: 0
Относительная модель и grid search: 76.5 с

scenario                                        Без продаж  ...  С продажами, L 28–42
method                               window                 ...
Baseline                             M035–M051     155.995  ...               151.394
                                     M052–M068     105.410  ...                99.279
                                     M069–M085     157.123  ...               132.333
Текущая Ridge                        M035–M051     156.285  ...               136.536
                                     M052–M068      73.740  ...                65.291
                                     M069–M085     150.871  ...               127.162
Относительная Ridge, alpha=10        M035–M051     157.108  ...               137.731
                                     M052–M068      74.431  ...                66.052
                                     M069–M085     150.199  ...               129.273
Относительная Ridge, внутренний grid M035–M051     151.485  ...               133.030
                                     M052–M068      74.892  ...                65.293
                                     M069–M085     150.199  ...               129.273

[12 rows x 4 columns]

                                           R1       R2  ...        S  Изменение S, %
Метод                                                   ...
Baseline                              154.386  104.542  ...  139.155           9.799
Текущая Ridge                         149.613   71.426  ...  126.736           0.000
Относительная Ridge, alpha=10         150.554   71.903  ...  127.196           0.363
Относительная Ridge, внутренний grid  145.239   72.279  ...  125.961          -0.611

[4 rows x 7 columns]

                                      Выигрыш ≥2%  ...  Принять
Метод                                              ...
Относительная Ridge, alpha=10               False  ...    False
Относительная Ridge, внутренний grid        False  ...    False

[2 rows x 6 columns]

method  Baseline  ...  Относительная Ridge, внутренний grid
zone              ...
1           49.5  ...                                  63.3
2           62.0  ...                                  52.6
3           70.2  ...                                  74.7
4          126.0  ...                                 141.6
5          148.2  ...                                 135.4
6          336.1  ...                                 308.3
7          156.2  ...                                 139.4
8           65.4  ...                                  59.2

[8 rows x 4 columns]

method  Baseline  ...  Относительная Ridge, внутренний grid
zone              ...
1           45.1  ...                                  35.2
2           29.6  ...                                  21.5
3           57.3  ...                                  67.8
4          117.6  ...                                  79.6
5          111.4  ...                                 106.0
6          209.6  ...                                  72.1
7           85.7  ...                                  97.8
8           60.9  ...                                  56.3

[8 rows x 4 columns]

method  Baseline  ...  Относительная Ridge, внутренний grid
zone              ...
1           31.5  ...                                  39.5
2           55.1  ...                                  42.5
3           74.4  ...                                  72.2
4          137.9  ...                                 156.8
5          118.6  ...                                 115.8
6          272.9  ...                                 272.5
7          232.5  ...                                 200.7
8           77.9  ...                                  53.4

[8 rows x 4 columns]

## 12. Проверка новых моделей на утечки

1. OK: признаки из известного расписания; комментарии доступности в relative_calendar
и choose_relative_alpha. Абонементы/КХЛ не добавлены.
2. OK: center, относительный ответ и веса считаются только из fitting history.
Это преобразование обучающего ответа; истинного ответа query среди признаков нет.
3. OK: прежние срезы и веса; внутренние продажи тоже строго до своего cutoff.
4. OK: внешние и внутренние блоки по времени, по 17 матчей, все восемь зон вместе.
5. OK: преобразования и Ridge fit только на fitting; выбор alpha только по более
ранним завершённым матчам history. Внешние ответы не выбирают параметры.
6. OK: исторические границы sold/seats прежние. Доступность окончательных
исторических абонементов НЕ ОПРЕДЕЛЕНА, они не используются. Test не рассчитывается.
7. Контроль baseline/текущей модели выполняется перед интерпретацией новых чисел.
Независимая итоговая оценка отсутствует: все внешние окна уже использованы ранее.
Внутренний подбор предотвращает прямой выбор alpha по внешним ответам,
но не отменяет прежнее использование внешних окон для выбора общей идеи.

In [16]:
import json

relative_report = {
    "scores": json.loads(scores.to_json(orient="index", force_ascii=False, double_precision=12)),
    "windows": json.loads(window_results.reset_index().to_json(orient="records", force_ascii=False, double_precision=12)),
    "zones": json.loads(zone_rmse.rename("R").reset_index().to_json(orient="records", force_ascii=False, double_precision=12)),
    "acceptance": json.loads(acceptance.to_json(orient="index", force_ascii=False)),
    "choices": list(grid_cache.values()),
    "seconds": time.perf_counter() - relative_started,
}

## 13. Вывод об относительной модели и подборе параметров

Фиксированная относительная Ridge: S=127.196,
на 0.363% хуже текущей Ridge.
После внутреннего grid search: S=125.961,
на 0.611% лучше текущей Ridge
и на 0.971% лучше фиксированного относительного варианта.

Grid search дал небольшой измеренный выигрыш. Однако улучшилось только
первое внешнее окно: R=145.239/72.279/143.163
против 149.613/71.426/142.952.
Для замены нужны ≥2% выигрыша S и минимум два улучшенных окна.
Обе относительные модели отклоняем по прежним условиям; сохраняем текущую Ridge.

Подбор выбирал alpha=100 в пяти уникальных историях и alpha=10 в одной.
Fallback не потребовался; в каждой history было ≥34 завершённых матчей.
Одно и то же состояние истории использовалось в нескольких датах отсечки;
эти шесть выборов не являются шестью независимыми экспериментами.
На последнем внешнем окне внутренний подбор оставил alpha=10.

Grid search выбирает лучшее среди заданных значений на внутренней проверке,
а не гарантированно оптимальный параметр для будущих матчей. Проверка только
на одном внутреннем блоке чувствительна к особенностям этого блока.
Параметры CatBoost в этой серии не подбирались.

Новая серия заняла 76.5 с. Внутренний подбор не использовал
внешние ответы, но три внешних окна уже были использованы для выбора общей
модели ранее. Независимой итоговой оценки нет, качество скрытого test неизвестно.
Финальные прогнозы и PROTOCOL не менялись.

## 14. Общий спрос и сезонные доли

Одна модель прогнозирует общий итог обычных билетов матча; затем распределяем
его между восемью зонами. В обучении общего спроса одна строка на матч.
Признаки прежние, кроме зоны: соперник, день недели, месяц, время начала,
номер домашнего матча сезона. Ridge учит отклонение общего итога от среднего
сезона. Сглаженный сезонный уровень и штраф alpha=10 фиксированы до расчёта.
При меньшем числе обучающих строк этот штраф действует иначе, чем в модели зон;
его не подбираем после просмотра результата этой гипотезы.

Для завершённого матча доля зоны — её tickets_total / сумма по всем зонам.
Среднее долей по матчам даёт общую историю распределения. Среднее текущего
сезона сглаживаем к общей истории с w=n/(n+8). Это среднее долей отдельных
матчей, а не доля в сумме билетов всех матчей. Матчи с нулевым общим итогом
не дают определённой доли и исключаются только из обучения распределения.
Доли не используют вместимость или абонементы.

До собственных продаж P0[матч,зона]=T_hat[матч]*share_hat[сезон,зона].
Доли нормируются внутри полного набора восьми зон матча. После распределения
применяем прежнюю поправку ранних продаж по зонам и общие границы/округление.
Поэтому окончательная сумма после поправок может отличаться от T_hat.

Сравниваем с baseline, принятой Ridge и относительной Ridge с внутренним grid.
Сценарный режим, проверочные примеры и критерии выбора не меняются.
Все три окна уже использовались ранее; независимого итогового теста нет.

In [17]:
total_alpha = 10
allocation_name = "Общий спрос + сезонные доли"
total_categories = [c for c in categorical_features if c != "zone"]


@threadpool_limits.wrap(limits=1, user_api="blas")
def total_calendar(history, query):
    # Доступен на момент: полные итоги завершённых history и известное расписание.
    columns = ["match_id", "season"] + total_categories + numeric_features
    fitting = history[columns].drop_duplicates("match_id").copy()
    totals = history.groupby("match_id")["tickets_total"].sum()
    fitting["tickets_total"] = fitting["match_id"].map(totals)
    checking = query[columns].drop_duplicates("match_id").copy()
    # Служебная единственная зона позволяет переиспользовать season_level.
    fitting["zone"] = "TOTAL"
    checking["zone"] = "TOTAL"
    centers = fitting.groupby("season")["tickets_total"].transform("mean")
    preprocessing = ColumnTransformer([
        ("categories", OneHotEncoder(handle_unknown="ignore", sparse_output=False),
         total_categories),
        ("number", StandardScaler(), numeric_features),
    ])
    model = make_pipeline(preprocessing, Ridge(alpha=total_alpha, random_state=42))
    model.fit(model_features(fitting), fitting["tickets_total"] - centers)
    total_prediction = season_level(fitting, checking) + model.predict(model_features(checking))
    return pd.Series(np.maximum(total_prediction, 0), index=checking["match_id"])

### Распределение между зонами

Используем общий код сезонного сглаживания. Во временной таблице вместо
билетных итогов помещаем доли: функция season_level тогда возвращает среднюю
долю зоны. Ни история, ни запрос при этом не изменяются.
Обучение долей и общего спроса получает одну и ту же доступную history.

In [18]:
def seasonal_zone_shares(history, query):
    # Доступен на момент: только распределение завершённых матчей history.
    totals = history.groupby("match_id")["tickets_total"].transform("sum")
    share_history = history.loc[totals > 0].copy()
    share_history["tickets_total"] = history.loc[totals > 0, "tickets_total"] / totals[totals > 0]
    shares = pd.Series(season_level(share_history, query), index=query.index)
    normalizer = shares.groupby(query["match_id"]).transform("sum")
    return (shares / normalizer).to_numpy()


def allocated_calendar(history, query):
    # Доступен на момент: обе ступени fit только на завершённой history.
    total_prediction = total_calendar(history, query)
    shares = seasonal_zone_shares(history, query)
    return query["match_id"].map(total_prediction).to_numpy() * shares

## 15. Сравнение и проверка распределения

Пересчитываем все четыре метода на прежних 984 примерах каждого метода.
Ответ query присоединяется после прогноза общей функцией evaluate_calendar.
Относительный grid остаётся прежним, без расширения сетки.

Для каждой даты отсечки также проверяем сумму долей и распределённый итог.
Показываем только максимальные расхождения, без таблицы индивидуальных продаж.
Эти проверки относятся к календарному прогнозу до поправки собственных продаж.

In [19]:
actual_totals = train.set_index(keys)["tickets_total"]
allocation_started = time.perf_counter()
allocation_parts = [evaluate_calendar(zone_mean, "Baseline"),
                    evaluate_calendar(calendar_forecast, "Текущая Ridge"),
                    evaluate_calendar(tuned_relative_calendar, grid_name),
                    evaluate_calendar(allocated_calendar, allocation_name)]
method_names = ["Baseline", "Текущая Ridge", grid_name, allocation_name]
validation = pd.concat(allocation_parts, ignore_index=True)
series_source = nbformat.read(root / "notebooks/Three_demand_hypotheses.ipynb", as_version=4)
exec(series_source.cells[11].source)
exec(series_source.cells[13].source)
exec(series_source.cells[15].source)
if not np.isclose(scores.loc[grid_name, "S"], 125.961054291514, rtol=0, atol=1e-8):
    raise ValueError("Контроль прежнего внутреннего grid не воспроизведён.")
print("Относительный grid воспроизведён.")
print("Изменение S к grid, %:",
      100 * (scores.loc[allocation_name, "S"] / scores.loc[grid_name, "S"] - 1))

Завершён метод: Baseline
Завершён метод: Текущая Ridge
Завершён метод: Относительная Ridge, внутренний grid
Завершён метод: Общий спрос + сезонные доли
Baseline и текущая модель воспроизведены.
M035–M051
M052–M068
M069–M085
Относительный grid воспроизведён.
Изменение S к grid, %: 1.3848856627292294

scenario                                        Без продаж  ...  С продажами, L 28–42
method                               window                 ...
Baseline                             M035–M051     155.995  ...               151.394
                                     M052–M068     105.410  ...                99.279
                                     M069–M085     157.123  ...               132.333
Текущая Ridge                        M035–M051     156.285  ...               136.536
                                     M052–M068      73.740  ...                65.291
                                     M069–M085     150.871  ...               127.162
Относительная Ridge, внутренний grid M035–M051     151.485  ...               133.030
                                     M052–M068      74.892  ...                65.293
                                     M069–M085     150.199  ...               129.273
Общий спрос + сезонные доли          M035–M051     153.601  ...               134.934
                                     M052–M068      74.028  ...                65.337
                                     M069–M085     153.892  ...               130.185

[12 rows x 4 columns]

                                           R1       R2  ...        S  Изменение S, %
Метод                                                   ...
Baseline                              154.386  104.542  ...  139.155           9.799
Текущая Ridge                         149.613   71.426  ...  126.736           0.000
Относительная Ridge, внутренний grid  145.239   72.279  ...  125.961          -0.611
Общий спрос + сезонные доли           147.283   71.608  ...  127.705           0.765

[4 rows x 7 columns]

                                      Выигрыш ≥2%  ...  Принять
Метод                                              ...
Относительная Ridge, внутренний grid        False  ...    False
Общий спрос + сезонные доли                 False  ...    False

[2 rows x 6 columns]

method  Baseline  ...  Общий спрос + сезонные доли
zone              ...
1           49.5  ...                         59.1
2           62.0  ...                         55.5
3           70.2  ...                         76.4
4          126.0  ...                        149.5
5          148.2  ...                        135.6
6          336.1  ...                        313.1
7          156.2  ...                        137.1
8           65.4  ...                         59.7

[8 rows x 4 columns]

method  Baseline  ...  Общий спрос + сезонные доли
zone              ...
1           45.1  ...                         33.7
2           29.6  ...                         22.2
3           57.3  ...                         68.7
4          117.6  ...                         78.3
5          111.4  ...                        105.4
6          209.6  ...                         67.5
7           85.7  ...                         99.0
8           60.9  ...                         55.4

[8 rows x 4 columns]

method  Baseline  ...  Общий спрос + сезонные доли
zone              ...
1           31.5  ...                         32.2
2           55.1  ...                         45.7
3           74.4  ...                         69.3
4          137.9  ...                        152.4
5          118.6  ...                        114.2
6          272.9  ...                        276.8
7          232.5  ...                        213.6
8           77.9  ...                         63.4

[8 rows x 4 columns]

### Сумма долей и общий календарный итог

Проверка обнаружит ошибку группировки или перепутанный порядок строк.
Все запросы проверки содержат восемь зон матча. Прогнозируемый общий итог
сравнивается с суммой распределённых прогнозов, а не с неизвестным ответом query.

In [20]:
allocation_checks = []
for (window, cutoff), query in examples.groupby(["window", "cutoff"]):
    first_id = query["window_start"].iloc[0]
    history = train.loc[(train["match_id"] < first_id) & (train["date"] < cutoff)]
    shares = pd.Series(seasonal_zone_shares(history, query), index=query.index)
    total_prediction = total_calendar(history, query)
    distributed = query["match_id"].map(total_prediction).to_numpy() * shares.to_numpy()
    distributed_sum = pd.Series(distributed, index=query.index).groupby(query["match_id"]).sum()
    allocation_checks.append({
        "share_error": float((shares.groupby(query["match_id"]).sum() - 1).abs().max()),
        "total_error": float((distributed_sum - total_prediction.reindex(distributed_sum.index)).abs().max()),
    })
allocation_checks = pd.DataFrame(allocation_checks)
print("Максимальное расхождение суммы долей с1:", allocation_checks["share_error"].max())
print("Максимальное расхождение общего итога, билетов:", allocation_checks["total_error"].max())
if allocation_checks["share_error"].max() > 1e-10 or allocation_checks["total_error"].max() > 1e-8:
    raise ValueError("Распределение нарушает сумму долей или общий календарный итог.")
print(f"Сравнение и диагностика распределения: {time.perf_counter() - allocation_started:.1f} с")

Максимальное расхождение суммы долей с1: 0.0
Максимальное расхождение общего итога, билетов: 9.094947017729282e-13
Сравнение и диагностика распределения: 74.6 с

## 16. Проверка двухступенчатой модели на утечки

1. OK: total_calendar и seasonal_zone_shares получают history и query,
используют только завершённые ответы history и известное расписание query.
2. OK: центры общего ответа, сезонный уровень и доли обучаются только на history.
Число матчей для сглаживания относится к этой же истории.
3. OK: собственные продажи и аналоги обрезаются прежними функциями по cutoff;
сценарные примеры, веса и состав одинаковы у всех четырёх методов.
4. OK: окна идут по времени, все восемь зон одного матча вместе;
исключены весь проверочный блок и незавершённые к cutoff матчи.
5. OK: encoder, scaler, Ridge fit только history. alpha=10 и prior=8 фиксированы.
Прежний относительный grid использует только внутреннюю history.
6. OK: границы исторической проверки sold/seats прежние. Доля зоны означает
часть обычных билетов матча, не долю заполнения мест. Исторические итоговые
абонементы и КХЛ не используются. Test и итоговый CSV не рассчитываются.
7. Контроль baseline/текущей Ridge/прежнего grid выполняется программно.
Числа характеризуют ранее использованные окна выбора; независимого теста нет.

In [21]:
import json

allocation_report = {
    "scores": json.loads(scores.to_json(orient="index", force_ascii=False, double_precision=12)),
    "windows": json.loads(window_results.reset_index().to_json(orient="records", force_ascii=False, double_precision=12)),
    "zones": json.loads(zone_rmse.rename("R").reset_index().to_json(orient="records", force_ascii=False, double_precision=12)),
    "acceptance": json.loads(acceptance.to_json(orient="index", force_ascii=False)),
    "checks": allocation_checks.max().to_dict(),
    "seconds": time.perf_counter() - allocation_started,
}

## 17. Вывод о прогнозе общего спроса

Двухступенчатая модель: S=127.705, на 0.765% хуже
принятой Ridge (S=126.736). Относительный grid остаётся
лучшим экспериментальным S=125.961, но он также не прошёл
условия принятия. Новый кандидат хуже него на
1.385%.

Общие ошибки нового кандидата R=147.283/71.608/145.965.
Первое окно улучшилось, второе и третье немного ухудшились относительно
принятой модели. Условия замены ≥2% выигрыша S и ≥2 улучшенных окна
не выполнены. Сохраняем принятую Ridge и финальные артефакты.

В последнем окне ошибки зон6/7 выросли с
273.7/206.2 до
276.8/213.6 билета.
Эта конфигурация не уменьшила основную проблемную часть ошибки.
Из этого запуска нельзя определить, какая из ступеней ответственна за разницу;
параметры и более гибкое распределение здесь не подбирались.

Покрытие текущего сезона в доступной истории: первое окно0 матчей,
второе11–17, третье0. Поэтому в третьем окне модель использует распределение
из прошлых сезонов; сведения о новом распределении сезона2025/26 ей ещё
недоступны. Это ограничение переноса, а не доказательство причины всей ошибки.

Распределение технически корректно: сумма долей равна1, максимальное
расхождение календарного общего итога с суммой зон
9.09e-13 билета. Проверка на утечки пройдена,
baseline, принятая Ridge и прежний относительный grid воспроизведены.
Серия заняла 74.6с. Независимого итогового теста нет:
все три окна уже использовались для выбора модели.
Финальный notebook, outputs/predictions.csv, PROTOCOL и данные не менялись.

## 18. Две новые группы: результаты КХЛ и покупки абонементов

План до запуска: сравнить каждую группу **отдельно** с принятой Ridge, alpha=10, seed42. Подбор параметров и комбинация групп в эту серию не входят. Сохраняем сценарный протокол предыдущих экспериментов по прямому поручению, включая заморозку КХЛ на 26 дней; поздний раздел PROTOCOL про отдельную процедуру финального дня здесь не применяется.

КХЛ: две доли побед — «Авангарда» и соперника. Только Regular season; доля текущего сезона сглаживается к известной доле прошлого сезона с силой 8 игр. Если прошлого сезона нет, исходная доля 0.5. Результаты известны по cutoff−26 дней включительно (15 декабря → 19 ноября). Ничья в источнике отсутствует; победа определяется сравнением голов.

Абонементы: log(1+число известных покупок) за сезон и последние 30 дней, по зоне, только date<cutoff. Суммируем abonements по пакетам. Это активность покупок, **не** число уникальных людей, занятых мест или абонементов конкретной игры. Явное поручение проверить активность покупок позволяет эту гипотезу при неизвестной привязке пакетов; финальные season_tickets в признаки не входят.

Для исторического обучения берём ту же дальность прогноза, что у query: cutoff_history = date_history − (date_query − cutoff_query). Эти отсечки строго раньше исторических игр и внешнего cutoff. При разных дальностях внутри query переобучаем одинаковую Ridge на одной и той же завершённой history. Query получает фактический cutoff. Преобразования обучаются только на history. Ни итоговый ноутбук, ни CSV не записываются.

In [22]:
khl = pd.read_csv(root / "data/khl_games.csv", parse_dates=["date"])
abon = pd.read_csv(root / "data/season_tickets_daily.csv", parse_dates=["date"])
assert not (khl["home_goals"] == khl["away_goals"]).any()
assert abon["abonements"].ge(0).all()
regular = khl.loc[khl["stage"].eq("Regular season")].copy()
home = regular[["season", "date", "home"]].rename(columns={"home": "team"})
home["wins"] = (regular["home_goals"] > regular["away_goals"]).astype(int)
away = regular[["season", "date", "away"]].rename(columns={"away": "team"})
away["wins"] = (regular["away_goals"] > regular["home_goals"]).astype(int)
team_games = pd.concat([home, away], ignore_index=True)
team_arrays = {}
for key, group in team_games.groupby(["season", "team"]):
    group = group.sort_values("date")
    team_arrays[key] = (group["date"].to_numpy(), group["wins"].cumsum().to_numpy())
abon_arrays = {}
for key, group in abon.groupby(["season", "zone"]):
    daily = group.groupby("date")["abonements"].sum().sort_index()
    abon_arrays[key] = (daily.index.to_numpy(), daily.cumsum().to_numpy())
print("КХЛ: последняя дата", khl["date"].max().date())
print("Абонементы: последняя дата", abon["date"].max().date())

КХЛ: последняя дата 2025-11-19
Абонементы: последняя дата 2025-11-23

In [23]:
KHL_LAG = 26
WIN_PRIOR = 8
RECENT_DAYS = 30
AVANGARD = "HC Avangard Omsk"
khl_columns = ["avangard_win_rate", "opponent_win_rate"]
abon_columns = ["abon_season_log", "abon_recent_log"]


def known_games(season, team, limit):
    arrays = team_arrays.get((season, team))
    if arrays is None:
        return 0, 0
    dates, cumulative = arrays
    count = np.searchsorted(dates, np.datetime64(limit), side="right")
    return int(count), int(cumulative[count - 1]) if count else 0


def win_rate(season, team, cutoff):
    # Доступен на момент: результаты Regular season по cutoff−26 дней включительно.
    limit = pd.Timestamp(cutoff) - pd.Timedelta(days=KHL_LAG)
    year = int(season[:4]) - 1
    previous = f"{year}/{str(year + 1)[-2:]}"
    old_count, old_wins = known_games(previous, team, limit)
    prior = old_wins / old_count if old_count else 0.5
    count, wins = known_games(season, team, limit)
    return (wins + WIN_PRIOR * prior) / (count + WIN_PRIOR)


def khl_features(frame, cutoffs):
    rows = []
    for (_, row), cutoff in zip(frame.iterrows(), cutoffs):
        rows.append([win_rate(row["season"], AVANGARD, cutoff),
                     win_rate(row["season"], row["opponent_khl"], cutoff)])
    return pd.DataFrame(rows, index=frame.index, columns=khl_columns)

In [24]:
def known_abon(season, zone, cutoff):
    arrays = abon_arrays.get((season, zone))
    if arrays is None:
        return 0
    dates, cumulative = arrays
    count = np.searchsorted(dates, np.datetime64(cutoff), side="left")
    return int(cumulative[count - 1]) if count else 0


def abon_features(frame, cutoffs):
    # Доступен на момент: покупки своего сезона/зоны строго до cutoff.
    # Пакеты суммируются как активность; занятые места матча не восстанавливаются.
    rows = []
    for (_, row), cutoff in zip(frame.iterrows(), cutoffs):
        total = known_abon(row["season"], row["zone"], cutoff)
        earlier = known_abon(row["season"], row["zone"],
                             cutoff - pd.Timedelta(days=RECENT_DAYS))
        rows.append(np.log1p([total, total - earlier]))
    return pd.DataFrame(rows, index=frame.index, columns=abon_columns)

In [25]:
@threadpool_limits.wrap(limits=1, user_api="blas")
def extended_calendar(history, query, feature_function, extra_columns):
    # Доступен на момент: завершённая history и признаки на своих отсечках.
    result = pd.Series(index=query.index, dtype=float)
    remaining = (query["date"] - query["cutoff"]).dt.days
    assert remaining.gt(0).all()
    centers = history.groupby(["zone", "season"])["tickets_total"].transform("mean")
    deviations = history["tickets_total"] - centers
    for horizon, group in query.groupby(remaining):
        history_cutoffs = history["date"] - pd.Timedelta(days=int(horizon))
        assert history_cutoffs.lt(history["date"]).all()
        assert history_cutoffs.lt(group["cutoff"].min()).all()
        x_history = model_features(history).join(feature_function(history, history_cutoffs))
        x_query = model_features(group).join(feature_function(group, group["cutoff"]))
        preprocessing = ColumnTransformer([
            ("categories", OneHotEncoder(handle_unknown="ignore", sparse_output=False),
             categorical_features),
            ("number", StandardScaler(), numeric_features + extra_columns),
        ])
        model = make_pipeline(preprocessing, Ridge(alpha=10, random_state=42))
        model.fit(x_history, deviations)
        result.loc[group.index] = season_level(history, group) + model.predict(x_query)
    return result.to_numpy()


def khl_calendar(history, query):
    return extended_calendar(history, query, khl_features, khl_columns)


def abon_calendar(history, query):
    return extended_calendar(history, query, abon_features, abon_columns)

### 19. Проверки отсечек до оценки

Для каждого источника сравниваем быстрые накопительные суммы с прямым фильтром исходных записей. Проверяем границы «в тот же день», конечность признаков и отсутствие будущих строк. Для каждого внешнего примера история остаётся прежней. Пробная пустая группа должна воспроизвести календарную Ridge: смена организации вычислений сама по себе результат не улучшает.

In [26]:
for (season, team), group in team_games.groupby(["season", "team"]):
    for cutoff in [group["date"].min(), group["date"].max(), pd.Timestamp("2025-11-19")]:
        selected = group.loc[group["date"].le(cutoff)]
        assert known_games(season, team, cutoff) == (len(selected), int(selected["wins"].sum()))
for (season, zone), group in abon.groupby(["season", "zone"]):
    for cutoff in [group["date"].min(), group["date"].max(), pd.Timestamp("2025-12-15")]:
        selected = group.loc[group["date"].lt(cutoff)]
        assert known_abon(season, zone, cutoff) == selected["abonements"].sum()
assert pd.Timestamp("2025-12-15") - pd.Timedelta(days=KHL_LAG) == pd.Timestamp("2025-11-19")


def empty_features(frame, cutoffs):
    return pd.DataFrame(index=frame.index)


window, cutoff = next(iter(examples.groupby(["window", "cutoff"])))[0]
probe = examples.loc[examples["window"].eq(window) & examples["cutoff"].eq(cutoff)]
history = train.loc[(train["match_id"] < probe["window_start"].iloc[0]) & (train["date"] < cutoff)]
np.testing.assert_allclose(extended_calendar(history, probe, empty_features, []),
                           calendar_forecast(history, probe), rtol=0, atol=1e-8)
for function in [khl_features, abon_features]:
    values = function(examples, examples["cutoff"])
    assert np.isfinite(values.to_numpy()).all()
print("Прямые фильтры источников, границы дат и контроль пустой группы: OK")

Прямые фильтры источников, границы дат и контроль пустой группы: OK

### 20. Сравнение групп на прежних примерах

Baseline и принятую Ridge рассчитываем заново. Затем сначала КХЛ, потом абонементы. Обе группы добавляются к принятой Ridge самостоятельно, поэтому можно отделить их пользу. Параметры, окна, поправка продаж и ограничения не меняются; всего 984 прогноза на метод.

In [27]:
import time
source_groups_started = time.perf_counter()
actual_totals = train.set_index(keys)["tickets_total"]
khl_name = "Ridge + КХЛ"
abon_name = "Ridge + покупки абонементов"
method_names = ["Baseline", "Текущая Ridge", khl_name, abon_name]
validation = pd.concat([
    evaluate_calendar(zone_mean, method_names[0]),
    evaluate_calendar(calendar_forecast, method_names[1]),
    evaluate_calendar(khl_calendar, khl_name),
    evaluate_calendar(abon_calendar, abon_name),
], ignore_index=True)
assert validation.groupby("method").size().eq(984).all()
print("Одинаковое число прогнозов у всех методов: 984")

Завершён метод: Baseline
Завершён метод: Текущая Ridge
Завершён метод: Ridge + КХЛ
Завершён метод: Ridge + покупки абонементов
Одинаковое число прогнозов у всех методов: 984

In [28]:
exec(compile(nbformat.read(root / "notebooks/Three_demand_hypotheses.ipynb", 4).cells[11].source,
             "source_groups_scores", "exec"))
exec(compile(nbformat.read(root / "notebooks/Three_demand_hypotheses.ipynb", 4).cells[13].source,
             "source_groups_acceptance", "exec"))

Baseline и текущая модель воспроизведены.

scenario                               Без продаж  ...  С продажами, L 28–42
method                      window                 ...
Baseline                    M035–M051     155.995  ...               151.394
                            M052–M068     105.410  ...                99.279
                            M069–M085     157.123  ...               132.333
Текущая Ridge               M035–M051     156.285  ...               136.536
                            M052–M068      73.740  ...                65.291
                            M069–M085     150.871  ...               127.162
Ridge + КХЛ                 M035–M051     163.662  ...               137.919
                            M052–M068      79.809  ...                68.640
                            M069–M085     151.615  ...               124.849
Ridge + покупки абонементов M035–M051     154.556  ...               138.010
                            M052–M068      73.641  ...                65.807
                            M069–M085     151.884  ...               127.856

[12 rows x 4 columns]

                                  R1       R2  ...        S  Изменение S, %
Метод                                          ...
Baseline                     154.386  104.542  ...  139.155           9.799
Текущая Ridge                149.613   71.426  ...  126.736           0.000
Ridge + КХЛ                  155.065   78.275  ...  129.706           2.344
Ridge + покупки абонементов  148.927   71.460  ...  127.028           0.230

[4 rows x 7 columns]

                             Выигрыш ≥2%  ...  Принять
Метод                                     ...
Ridge + КХЛ                        False  ...    False
Ridge + покупки абонементов        False  ...    False

[2 rows x 6 columns]

In [29]:
exec(compile(nbformat.read(root / "notebooks/Three_demand_hypotheses.ipynb", 4).cells[15].source,
             "source_groups_zones", "exec"))

M035–M051
M052–M068
M069–M085

method  Baseline  Текущая Ridge  Ridge + КХЛ  Ridge + покупки абонементов
zone
1           49.5           73.2         63.7                         77.4
2           62.0           63.7         79.7                         59.8
3           70.2           82.7         92.9                         81.5
4          126.0          139.3        123.6                        146.2
5          148.2          141.1        144.4                        140.5
6          336.1          311.5        330.2                        305.2
7          156.2          145.3        152.4                        145.6
8           65.4           73.0         70.5                         75.7

method  Baseline  Текущая Ridge  Ridge + КХЛ  Ridge + покупки абонементов
zone
1           45.1           38.2         48.3                         41.1
2           29.6           35.1         39.1                         35.8
3           57.3           68.9         74.0                         69.8
4          117.6           78.5         91.4                         81.9
5          111.4           99.6        108.8                         98.6
6          209.6           75.6         62.7                         71.0
7           85.7           96.2        109.3                         95.7
8           60.9           48.2         60.1                         48.8

method  Baseline  Текущая Ridge  Ridge + КХЛ  Ridge + покупки абонементов
zone
1           31.5           44.5         43.3                         47.5
2           55.1           43.3         43.7                         43.0
3           74.4           69.4         69.5                         70.1
4          137.9          148.7        146.7                        152.7
5          118.6          113.2        113.2                        114.0
6          272.9          273.7        273.2                        275.9
7          232.5          206.2        207.1                        204.8
8           77.9           49.0         50.3                         46.6

In [30]:
import json
source_groups_report = {
    "scores": json.loads(scores.to_json(orient="index", force_ascii=False, double_precision=12)),
    "windows": json.loads(window_results.reset_index().to_json(orient="records", force_ascii=False, double_precision=12)),
    "zones": json.loads(zone_rmse.rename("R").reset_index().to_json(orient="records", force_ascii=False, double_precision=12)),
    "acceptance": json.loads(acceptance.to_json(orient="index", force_ascii=False)),
    "seconds": time.perf_counter() - source_groups_started,
}
print("Время сравнения, с:", round(source_groups_report["seconds"], 1))

Время сравнения, с: 51.0

### 21. Итог проверки новых источников

| Метод | R1 | R2 | R3 | S без продаж | S с продажами | S | Изменение S, % |
|---|---:|---:|---:|---:|---:|---:|---:|
| Baseline | 154.386436 | 104.541882 | 148.845803 | 143.912627 | 129.747859 | 139.154981 | 9.799233 |
| Ridge + КХЛ | 155.065125 | 78.275172 | 142.742579 | 136.675387 | 115.749845 | 129.706364 | 2.343870 |
| Ridge + покупки абонементов | 148.926702 | 71.459655 | 143.862604 | 132.991510 | 115.249675 | 127.027892 | 0.230440 |
| Текущая Ridge | 149.612789 | 71.425676 | 142.952450 | 132.941463 | 114.458891 | 126.735841 | 0.000000 |

Оба кандидата отклонены. КХЛ улучшает только третье окно, но ухудшает первые два; S хуже принятой Ridge на 2.343870%. Активность абонементов улучшает только первое окно; S хуже на 0.230440%. Параметры после просмотра результатов не подбирались, сочетание двух групп не проверялось. Это не доказательство бесполезности источников вообще: проверены конкретные простые признаки при alpha=10 и выбранных исторических срезах.

**Leakage-audit (номера ячеек от нуля):**
1. OK — КХЛ с передачей cutoff и границей cutoff−26 (48, строки 18–34); покупки date<cutoff (49, строки 1–19); исторические отсечки date−horizon и query cutoff (50, строки 6–14). Сравнение быстрых сумм с прямыми фильтрами, проверка границы 15.12→19.11 и пустой группы — 52.
2. OK — центры ответа и сезонный уровень только history (50, строки 7–8,22). Никакие проверочные ordinary tickets в признаки не входят.
3. OK — прежние sales_before/matched_history/sales_correction, единые examples и веса. По 984 прогноза на каждый метод (54). Будущие покупки абонементов не входят; связь package_matches с конкретными играми НЕ ОПРЕДЕЛЕНА, поэтому признак назван активностью, не занятостью мест.
4. OK — evaluate_calendar (21, строки 3–5) исключает весь проверочный блок и незавершённые матчи. Все 8 зон вместе, случайного разбиения нет.
5. OK — encoder/scaler и Ridge fit только history (50, строки 15–21); alpha10/seed42, WIN_PRIOR8 и RECENT_DAYS30 фиксированы до запуска. Все три окна уже участвовали в выборе, независимого итогового теста нет.
6. OK для исторической оценки — прежние границы sold/seats. Итоговые исторические season_tickets исключены. Test не прогнозировался, CSV не менялся; при будущем прогнозе КХЛ на 15.12 ограничится 19.11, покупки строго до 15.12, потолок seats−season_tickets остаётся обязательным.
7. OK — baseline139.154980934 и принятая Ridge126.735841108 воспроизведены с допуском 1e-8. Подозрительного скачка точности нет.

Вердикт: оценки пригодны для сравнения на этих повторно использованных окнах, но не являются независимой оценкой скрытого test. Сохраняем принятую модель. Результаты КХЛ раньше не использовались, теперь их простая группа измерена; первоначальная претензия «соперник вообще отсутствует» не подтверждена — его категория уже есть в исходной Ridge.